# Test REST API
### Test the REST API with a GET all contacts request
GET https://cse-341-proj1.onrender.com/contacts

### Test the REST API with a GET contact by ID request
GET https://cse-341-proj1.onrender.com/contacts/6826eaf4aafd6f848c0f09bb

### Test the REST API with a POST request to create a new contact
POST https://cse-341-proj1.onrender.com/contacts
Content-Type: application/json

{
    "firstName": "New",
    "lastName": "Farress",
    "email": "jfarress3@opera.com",
    "favoriteColor": "Purple",
    "birthDate": "8/30/2038"
}

### Test the REST API with a PUT request to update a contact
PUT https://cse-341-proj1.onrender.com/contacts/6826eaf4aafd6f848c0f09bb
Content-Type: application/json

{
    "firstName": "Joleen1",
    "lastName": "Farress1",
    "email": "jfarress31@opera.com",
    "favoriteColor": "Pink",
    "birthDate": "8/30/2020"
}

### Test the REST API with a DELETE request to delete a contact
DELETE https://cse-341-proj1.onrender.com/contacts/6826eaf4aafd6f848c0f09bb